### ISSUE TITLE
Unable to load the SpatiaLite library extension "mod_spatialite" because: mod_spatialite.so: undefined symbol: libiconv

### ISSUE THREAD

**Issue by korvinos** [nansencenter/geo-spaas-vagrant#11]
I am trying to deploy VM on my mac and get an error connected with spatialite. The error is related to an issue in mod_spatialite: `mod_spatialite.so: undefined symbol: libiconv`. I have tried to find a solution but it has been unsuccessful yet. Installation of `libiconv` from the source did not help

### Error report

```
vagrant@ubuntu-xenial:~/geospaas_doppler$ python manage.py makemigrations
/home/vagrant/miniconda/lib/python2.7/site-packages/nansat-1.0.20-py2.7-linux-x86_64.egg/nansat/nansatmap.py:47: NansatFutureWarning: Nansatmap() will be disabled in Nansat 1.1. and moved to a separate packageIt is not covered by unittests intentionally.
  warnings.warn(NANSATMAP_WARNING, NansatFutureWarning)
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 110, in handle
    loader.check_consistent_history(connection)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/db/migrations/loader.py", line 282, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/contrib/gis/db/backends/spatialite/base.py", line 65, in get_new_connection
    six.reraise(ImproperlyConfigured, ImproperlyConfigured(new_msg), sys.exc_info()[2])
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/contrib/gis/db/backends/spatialite/base.py", line 60, in get_new_connection
    cur.execute("SELECT load_extension(%s)", (self.spatialite_lib,))
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.core.exceptions.ImproperlyConfigured: Unable to load the SpatiaLite library extension "mod_spatialite" because: /home/vagrant/miniconda/lib/././mod_spatialite.so: undefined symbol: libiconv
```

**Comment by ShaneMill1** [comment]
Having this issue as well when building a Docker image using sqlite3 and and spatialite, and loading the module mod_spatialite into sqlite3.
